kind: pipeline
type: docker
name: Build and Push

steps:
  - name: Build Docker Image
    image: plugins/docker
    settings:
      repo: 192.168.100.6:5000/my-app
      registry: http://192.168.100.6:5000
      insecure: true # ✅ Skips TLS check
      dockerfile: Dockerfile
      tags:
        - latest

trigger:
  branch:
    - master
