kind: pipeline
type: docker
name: Build and Push Docker Image

steps:
  - name: Build Docker Image
    image: plugins/docker
    settings:
      repo: VerTrld/my-app  # Docker Hub repo
      registry: docker.io   # Docker Hub registry
      dockerfile: Dockerfile  # Make sure this is correct, relative to the repo's root
      tags: latest  # You can change this to a specific tag or use a dynamic one

trigger:
  event:
    - push    # Trigger the build when there is a push to GitHub
  branch:
    - master    # Trigger only on pushes to the 'main' branch
