kind: pipeline
type: docker
name: Build and Push to VPS

steps:
  - name: build
    image: plugins/docker
    settings:
      # tags: ${DRONE_TAG}
      dockerfile: Dockerfile
      repo: 128.199.250.178:5000/forum-app
      registry: 128.199.250.178:5000
      insecure: true 
      tags:
       - latest

trigger:
  branch:
    - master
