kind: pipeline
type: docker
name: Build and Push to Local Registry

steps:
  - name: Build Docker Image
    image: plugins/docker
    settings:
      repo: localhost:5000/my-app # Registry mo (local registry)
      registry: localhost:5000 # Same as above
      dockerfile: Dockerfile # Path to Dockerfile
      tags: latest # Tag (optional, e.g., 'latest')

trigger:
  branch:
    - master # O kung anong branch ang gusto mong mag-trigger ng build
