kind: pipeline
type: docker
name: Build and Push to VPS

steps:
  - name: build
    image: plugins/docker
    settings:
      tags: ${DRONE_TAG}
      dockerfile: Dockerfile
      registry: 128.199.126.16:5000
      repo: 128.199.250.178:5000/web-app
      insecure: true

trigger:
  branch:
    - master
