kind: pipeline
type: docker
name: dev

steps:
  - name: build
    image: plugins/docker
    settings:
      tags: ${DRONE_TAG}
      dockerfile: Dockerfile
      registry: 100.98.49.87:5000
      repo: 100.98.49.87:5000/forum-web
      insecure: true

trigger:
  branch:
    - master
