kind: pipeline
type: docker
name: Build and Push to Local Registry

steps:
  - name: Build Docker Image
    image: plugins/docker
    settings:
      repo: 172.26.113.89:5000/my-app  # Registry URL (replace with your local registry IP)
      registry: http://172.26.113.89:5000   # Same as above for remote registry
      dockerfile: Dockerfile           # Path to Dockerfile
      tags:
        - latest                      # Tag (optional, e.g., 'latest')

trigger:
  branch:
    - master  # Specify the branch to trigger the build
