kind: pipeline
type: docker
name: dev 

steps:
  - name: build
    image: plugins/docker
    settings:
      tags: ${DRONE_TAG}
      dockerfile: Dockerfile
      registry: 172.26.113.89:5000
      repo: 172.26.113.89:5000/web-app
      insecure: true

trigger:
  branch:
    - master
