kind: pipeline
type: docker
name: Build and Push to VPS

steps:
  - name: Build and Push Image to VPS Registry
    image: plugins/docker
    settings:
      repo: 128.199.250.178:5000/my-app
      registry: 128.199.250.178:5000
      insecure: true 
      dockerfile: Dockerfile
      tags:
        - latest

trigger:
  branch:
    - master
