version: "3"
services:
  nextjs-app:
    build:
      context: https://github.com/VerTrld/forum.git
      args:
        NEXT_PUBLIC_API_URL: http://139.59.126.55:3001
        NEXT_PUBLIC_AUTH_URL: http://139.59.126.55:3000
    ports:
      - "3000:3000"
    restart: always
